export const AUTHENTICATE = 'AUTHENTICATE'
export const DEAUTHENTICATE = 'DEAUTHENTICATE'

export const SET_USER = 'SET_USER'
export const RESET_USER = 'RESET_USER'
export const SET_FAVORITE_ANIME = 'SET_FAVORITE_ANIME'
export const SET_FAVORITE_MANGA = 'SET_FAVORITE_MANGA'
export const SET_UNFAVORITE_ANIME = 'SET_UNFAVORITE_ANIME'
export const SET_UNFAVORITE_MANGA = 'SET_UNFAVORITE_MANGA'
